var classes = [
    {
        "name": "App\\Config\\Config",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 11,
        "vocabulary": 11,
        "volume": 38.05,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 76.11,
        "number_operators": 0,
        "number_operands": 11,
        "number_operators_unique": 0,
        "number_operands_unique": 11,
        "cloc": 2,
        "loc": 18,
        "lloc": 16,
        "mi": 87.22,
        "mIwoC": 62.53,
        "commentWeight": 24.69,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Config\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\AboutController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\AboutTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\BasketController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 36,
        "vocabulary": 12,
        "volume": 129.06,
        "difficulty": 2.8,
        "effort": 361.36,
        "level": 0.36,
        "bugs": 0.04,
        "time": 20,
        "intelligentContent": 46.09,
        "number_operators": 8,
        "number_operands": 28,
        "number_operators_unique": 2,
        "number_operands_unique": 10,
        "cloc": 5,
        "loc": 28,
        "lloc": 23,
        "mi": 85.42,
        "mIwoC": 54.98,
        "commentWeight": 30.44,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\HomeController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\HomeTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\OrderController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendMail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildMessage",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 11,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Services\\FileStorage",
            "App\\Models\\Order",
            "App\\Services\\OrderDBStorage",
            "App\\Models\\Order",
            "App\\Services\\UserDBStorage",
            "App\\Views\\OrderTemplate",
            "App\\Services\\FileStorage",
            "App\\Models\\Order",
            "App\\Services\\OrderDBStorage",
            "App\\Models\\Order",
            "PHPMailer\\PHPMailer\\PHPMailer",
            "PHPMailer\\PHPMailer\\Exception"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 169,
        "vocabulary": 50,
        "volume": 953.81,
        "difficulty": 9.28,
        "effort": 8850.49,
        "level": 0.11,
        "bugs": 0.32,
        "time": 492,
        "intelligentContent": 102.79,
        "number_operators": 55,
        "number_operands": 114,
        "number_operators_unique": 7,
        "number_operands_unique": 43,
        "cloc": 13,
        "loc": 110,
        "lloc": 97,
        "mi": 59.71,
        "mIwoC": 34.32,
        "commentWeight": 25.39,
        "kanDefect": 0.94,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.41,
        "relativeSystemComplexity": 169.41,
        "totalStructuralComplexity": 676,
        "totalDataComplexity": 1.64,
        "totalSystemComplexity": 677.64,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\ProductController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Services\\FileStorage",
            "App\\Models\\Product",
            "App\\Services\\ProductDBStorage",
            "App\\Models\\Product",
            "App\\Views\\ProductTemplate",
            "App\\Views\\ProductTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 30,
        "vocabulary": 10,
        "volume": 99.66,
        "difficulty": 8,
        "effort": 797.26,
        "level": 0.13,
        "bugs": 0.03,
        "time": 44,
        "intelligentContent": 12.46,
        "number_operators": 14,
        "number_operands": 16,
        "number_operators_unique": 5,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 22,
        "lloc": 22,
        "mi": 56.18,
        "mIwoC": 56.18,
        "commentWeight": 0,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.75,
        "relativeSystemComplexity": 9.75,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 9.75,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\RegisterController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verify",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Views\\RegisterTemplate",
            "App\\Services\\UserDBStorage",
            "App\\Models\\User",
            "App\\Services\\ValidateRegisterData",
            "App\\Services\\Mailer",
            "App\\Services\\UserDBStorage",
            "App\\Views\\RegisterTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 101,
        "vocabulary": 31,
        "volume": 500.37,
        "difficulty": 5.04,
        "effort": 2520.4,
        "level": 0.2,
        "bugs": 0.17,
        "time": 140,
        "intelligentContent": 99.34,
        "number_operators": 33,
        "number_operands": 68,
        "number_operators_unique": 4,
        "number_operands_unique": 27,
        "cloc": 6,
        "loc": 60,
        "lloc": 54,
        "mi": 65.89,
        "mIwoC": 42.37,
        "commentWeight": 23.53,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.79,
        "relativeSystemComplexity": 49.79,
        "totalStructuralComplexity": 147,
        "totalDataComplexity": 2.38,
        "totalSystemComplexity": 149.38,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\UserController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "profile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateProfile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "history",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 17,
        "ccn": 12,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Views\\UserTemplate",
            "App\\Services\\UserDBStorage",
            "App\\Views\\UserTemplate",
            "App\\Services\\UserDBStorage",
            "App\\Views\\UserTemplate",
            "App\\Services\\ValidateBase",
            "App\\Services\\UserDBStorage",
            "App\\Services\\UserDBStorage",
            "App\\Views\\UserTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 4,
        "length": 136,
        "vocabulary": 31,
        "volume": 673.77,
        "difficulty": 8.37,
        "effort": 5636.35,
        "level": 0.12,
        "bugs": 0.22,
        "time": 313,
        "intelligentContent": 80.54,
        "number_operators": 49,
        "number_operands": 87,
        "number_operators_unique": 5,
        "number_operands_unique": 26,
        "cloc": 11,
        "loc": 94,
        "lloc": 83,
        "mi": 61.99,
        "mIwoC": 36.72,
        "commentWeight": 25.27,
        "kanDefect": 0.92,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.82,
        "relativeSystemComplexity": 100.82,
        "totalStructuralComplexity": 600,
        "totalDataComplexity": 4.91,
        "totalSystemComplexity": 604.91,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Models\\Order",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBasketData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prepareData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 7,
        "ccnMethodMax": 6,
        "externals": [
            "App\\Services\\ISaveStorage",
            "App\\Services\\FileStorage",
            "App\\Models\\Product",
            "App\\Services\\ProductDBStorage",
            "App\\Models\\Product"
        ],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 131,
        "vocabulary": 32,
        "volume": 655,
        "difficulty": 10.96,
        "effort": 7179.81,
        "level": 0.09,
        "bugs": 0.22,
        "time": 399,
        "intelligentContent": 59.75,
        "number_operators": 36,
        "number_operands": 95,
        "number_operators_unique": 6,
        "number_operands_unique": 26,
        "cloc": 11,
        "loc": 69,
        "lloc": 58,
        "mi": 69.86,
        "mIwoC": 40.87,
        "commentWeight": 28.99,
        "kanDefect": 0.89,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.42,
        "relativeSystemComplexity": 5.42,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 5.67,
        "totalSystemComplexity": 21.67,
        "package": "App\\Models\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "App\\Models\\Product",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Services\\ILoadStorage"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 11,
        "vocabulary": 5,
        "volume": 25.54,
        "difficulty": 2.67,
        "effort": 68.11,
        "level": 0.38,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 9.58,
        "number_operators": 3,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 1,
        "loc": 16,
        "lloc": 15,
        "mi": 83.24,
        "mIwoC": 64.36,
        "commentWeight": 18.88,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "package": "App\\Models\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Models\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Services\\ISaveStorage"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 13,
        "vocabulary": 6,
        "volume": 33.6,
        "difficulty": 2.5,
        "effort": 84.01,
        "level": 0.4,
        "bugs": 0.01,
        "time": 5,
        "intelligentContent": 13.44,
        "number_operators": 3,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 1,
        "loc": 16,
        "lloc": 15,
        "mi": 82.41,
        "mIwoC": 63.52,
        "commentWeight": 18.88,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "package": "App\\Models\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Routes\\Router",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getRoutes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "executeRoute",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleDefault",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "route",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 9,
        "ccnMethodMax": 6,
        "externals": [
            "route",
            "App\\Controllers\\HomeController"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 140,
        "vocabulary": 46,
        "volume": 773.3,
        "difficulty": 5.52,
        "effort": 4271.55,
        "level": 0.18,
        "bugs": 0.26,
        "time": 237,
        "intelligentContent": 139.99,
        "number_operators": 24,
        "number_operands": 116,
        "number_operators_unique": 4,
        "number_operands_unique": 42,
        "cloc": 32,
        "loc": 74,
        "lloc": 42,
        "mi": 85.73,
        "mIwoC": 43.16,
        "commentWeight": 42.57,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.13,
        "relativeSystemComplexity": 26.13,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 104.5,
        "package": "App\\Routes\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Services\\DBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PDO"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 1,
        "loc": 10,
        "lloc": 9,
        "mi": 100.47,
        "mIwoC": 76.94,
        "commentWeight": 23.53,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Services\\",
        "pageRank": 0.07,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "App\\Services\\FileStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Services\\ILoadStorage",
            "App\\Services\\ISaveStorage"
        ],
        "parents": [],
        "implements": [
            "App\\Services\\ILoadStorage",
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 2,
        "length": 47,
        "vocabulary": 14,
        "volume": 178.95,
        "difficulty": 8.61,
        "effort": 1540.92,
        "level": 0.12,
        "bugs": 0.06,
        "time": 86,
        "intelligentContent": 20.78,
        "number_operators": 16,
        "number_operands": 31,
        "number_operators_unique": 5,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 30,
        "lloc": 30,
        "mi": 51.6,
        "mIwoC": 51.6,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 9,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "App\\Services\\Mailer",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "sendOrderMail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendMailUserConfirmation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 9,
        "ccnMethodMax": 5,
        "externals": [
            "PHPMailer\\PHPMailer\\PHPMailer",
            "PHPMailer\\PHPMailer\\Exception",
            "PHPMailer\\PHPMailer\\PHPMailer",
            "PHPMailer\\PHPMailer\\Exception"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 117,
        "vocabulary": 26,
        "volume": 549.95,
        "difficulty": 11.7,
        "effort": 6434.43,
        "level": 0.09,
        "bugs": 0.18,
        "time": 357,
        "intelligentContent": 47,
        "number_operators": 39,
        "number_operands": 78,
        "number_operators_unique": 6,
        "number_operands_unique": 20,
        "cloc": 12,
        "loc": 81,
        "lloc": 69,
        "mi": 67.57,
        "mIwoC": 39.49,
        "commentWeight": 28.08,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.86,
        "relativeSystemComplexity": 36.86,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1.71,
        "totalSystemComplexity": 73.71,
        "package": "App\\Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Services\\OrderDBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveItems",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Services\\DBStorage",
            "App\\Services\\ISaveStorage"
        ],
        "parents": [
            "App\\Services\\DBStorage"
        ],
        "implements": [
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 1,
        "length": 80,
        "vocabulary": 28,
        "volume": 384.59,
        "difficulty": 4.02,
        "effort": 1546.05,
        "level": 0.25,
        "bugs": 0.13,
        "time": 86,
        "intelligentContent": 95.67,
        "number_operators": 13,
        "number_operands": 67,
        "number_operators_unique": 3,
        "number_operands_unique": 25,
        "cloc": 6,
        "loc": 33,
        "lloc": 27,
        "mi": 81.09,
        "mIwoC": 50.41,
        "commentWeight": 30.68,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.8,
        "relativeSystemComplexity": 16.8,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1.6,
        "totalSystemComplexity": 33.6,
        "package": "App\\Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Services\\ProductDBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Services\\DBStorage",
            "App\\Services\\ILoadStorage"
        ],
        "parents": [
            "App\\Services\\DBStorage"
        ],
        "implements": [
            "App\\Services\\ILoadStorage"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 8,
        "volume": 39,
        "difficulty": 1.5,
        "effort": 58.5,
        "level": 0.67,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 26,
        "number_operators": 4,
        "number_operands": 9,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 66.01,
        "mIwoC": 66.01,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 4.67,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Services\\UserDBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "uniqueEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveVerified",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loginUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUserData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateProfile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDataHistory",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Services\\DBStorage",
            "App\\Services\\ISaveStorage"
        ],
        "parents": [
            "App\\Services\\DBStorage"
        ],
        "implements": [
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 1,
        "length": 140,
        "vocabulary": 38,
        "volume": 734.71,
        "difficulty": 9.56,
        "effort": 7025.66,
        "level": 0.1,
        "bugs": 0.24,
        "time": 390,
        "intelligentContent": 76.83,
        "number_operators": 38,
        "number_operands": 102,
        "number_operators_unique": 6,
        "number_operands_unique": 32,
        "cloc": 8,
        "loc": 82,
        "lloc": 74,
        "mi": 61.48,
        "mIwoC": 38.21,
        "commentWeight": 23.26,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 1.79,
        "relativeSystemComplexity": 50.79,
        "totalStructuralComplexity": 343,
        "totalDataComplexity": 12.5,
        "totalSystemComplexity": 355.5,
        "package": "App\\Services\\",
        "pageRank": 0.04,
        "afferentCoupling": 4,
        "efferentCoupling": 2,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Services\\ValidateBase",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "sanitationString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sanitationArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 10,
        "vocabulary": 4,
        "volume": 20,
        "difficulty": 1.5,
        "effort": 30,
        "level": 0.67,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 13.33,
        "number_operators": 1,
        "number_operands": 9,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 65.62,
        "mIwoC": 65.62,
        "commentWeight": 0,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 3,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Services\\ValidateRegisterData",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 9,
        "ccnMethodMax": 9,
        "externals": [
            "App\\Services\\ValidateBase",
            "App\\Services\\UserDBStorage"
        ],
        "parents": [
            "App\\Services\\ValidateBase"
        ],
        "implements": [],
        "lcom": 1,
        "length": 69,
        "vocabulary": 22,
        "volume": 307.7,
        "difficulty": 7.88,
        "effort": 2423.14,
        "level": 0.13,
        "bugs": 0.1,
        "time": 135,
        "intelligentContent": 39.07,
        "number_operators": 27,
        "number_operands": 42,
        "number_operators_unique": 6,
        "number_operands_unique": 16,
        "cloc": 4,
        "loc": 44,
        "lloc": 40,
        "mi": 68.94,
        "mIwoC": 46.42,
        "commentWeight": 22.51,
        "kanDefect": 0.71,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 7,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 7,
        "package": "App\\Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Views\\AboutTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 8,
        "volume": 45,
        "difficulty": 1.67,
        "effort": 75,
        "level": 0.6,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 27,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 19,
        "lloc": 19,
        "mi": 60.39,
        "mIwoC": 60.39,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Views\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\BaseTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 44,
        "vocabulary": 19,
        "volume": 186.91,
        "difficulty": 6.92,
        "effort": 1293.98,
        "level": 0.14,
        "bugs": 0.06,
        "time": 72,
        "intelligentContent": 27,
        "number_operators": 14,
        "number_operands": 30,
        "number_operators_unique": 6,
        "number_operands_unique": 13,
        "cloc": 1,
        "loc": 101,
        "lloc": 100,
        "mi": 47.61,
        "mIwoC": 39.93,
        "commentWeight": 7.68,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Views\\",
        "pageRank": 0.26,
        "afferentCoupling": 6,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Views\\HomeTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 8,
        "volume": 45,
        "difficulty": 1.67,
        "effort": 75,
        "level": 0.6,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 27,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 47,
        "lloc": 47,
        "mi": 51.81,
        "mIwoC": 51.81,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Views\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\OrderTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getOrderTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "formOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 11,
        "ccnMethodMax": 9,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 2,
        "length": 112,
        "vocabulary": 32,
        "volume": 560,
        "difficulty": 13.83,
        "effort": 7746.67,
        "level": 0.07,
        "bugs": 0.19,
        "time": 430,
        "intelligentContent": 40.48,
        "number_operators": 29,
        "number_operands": 83,
        "number_operators_unique": 8,
        "number_operands_unique": 24,
        "cloc": 6,
        "loc": 115,
        "lloc": 108,
        "mi": 52.25,
        "mIwoC": 34.92,
        "commentWeight": 17.33,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 5.17,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 10.33,
        "package": "App\\Views\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\ProductTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getAllTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCardTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 2,
        "length": 72,
        "vocabulary": 24,
        "volume": 330.12,
        "difficulty": 5.9,
        "effort": 1947.69,
        "level": 0.17,
        "bugs": 0.11,
        "time": 108,
        "intelligentContent": 55.95,
        "number_operators": 13,
        "number_operands": 59,
        "number_operators_unique": 4,
        "number_operands_unique": 20,
        "cloc": 5,
        "loc": 68,
        "lloc": 63,
        "mi": 63.24,
        "mIwoC": 42.84,
        "commentWeight": 20.39,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 5,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\RegisterTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getRegisterTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "formRegister",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getVerifyTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 3,
        "length": 44,
        "vocabulary": 15,
        "volume": 171.9,
        "difficulty": 3.63,
        "effort": 623.15,
        "level": 0.28,
        "bugs": 0.06,
        "time": 35,
        "intelligentContent": 47.42,
        "number_operators": 15,
        "number_operands": 29,
        "number_operators_unique": 3,
        "number_operands_unique": 12,
        "cloc": 0,
        "loc": 56,
        "lloc": 56,
        "mi": 46.08,
        "mIwoC": 46.08,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 15,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\UserTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getUserTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFormLogin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProfileTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFormProfile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHistoryTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 7,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 5,
        "length": 126,
        "vocabulary": 35,
        "volume": 646.29,
        "difficulty": 9.31,
        "effort": 6017.18,
        "level": 0.11,
        "bugs": 0.22,
        "time": 334,
        "intelligentContent": 69.42,
        "number_operators": 36,
        "number_operands": 90,
        "number_operators_unique": 6,
        "number_operands_unique": 29,
        "cloc": 18,
        "loc": 123,
        "lloc": 105,
        "mi": 63.22,
        "mIwoC": 35.29,
        "commentWeight": 27.93,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.4,
        "relativeSystemComplexity": 10.4,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 52,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    }
]